from app.models import db, Pokemon

def seed_pokemon():
    Bulbasaur = Pokemon(
        name='Bulbasaur', 
        type='grass, poison', 
        personality='playful',
        bio= '',
        imgUrl= '')
    Ivysaur = Pokemon(
        name='Ivysaur', 
        type='grass, poison', 
        personality='logical',
        bio= '',
        imgUrl= '')
    Venusaur = Pokemon(
        name='Venusaur', 
        type='grass, poison', 
        personality='caring',
        bio= '',
        imgUrl= '')
    Charmander = Pokemon(
        name='Charmander', 
        type='fire', 
        personality='playful',
        bio= '',
        imgUrl= '')
    Charmeleon = Pokemon(
        name='Charmeleon', 
        type='fire', 
        personality='logical',
        bio= '',
        imgUrl= '')
    Charizard = Pokemon(
        name='Charizard', 
        type='fire, flying', 
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Squirtle = Pokemon(
        name='Squirtle', 
        type='water', 
        personality='playful',
        bio= '',
        imgUrl= '')
    Wartortle = Pokemon(
        name='Wartortle', 
        type='water', 
        personality='logical',
        bio= '',
        imgUrl= '')
    Blastoise = Pokemon(
        name='Blastoise', 
        type='water', 
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Caterpie = Pokemon(
        name='Caterpie', 
        type='grass, poison', 
        personality='playful',
        bio= '',
        imgUrl= '')
    Metapod = Pokemon(
        name='Metapod', 
        type='grass, poison', 
        personality='logical',
        bio= '',
        imgUrl= '')
    Butterfree = Pokemon(
        name='Butterfree', 
        type='grass, poison', 
        personality='caring',
        bio= '',
        imgUrl= '')
    Weedle = Pokemon(
        name='Weedle', 
        type='bug, poison', 
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Kakuna = Pokemon(
        name='Kakuna', 
        type='bug, poison', 
        personality='logical',
        bio= '',
        imgUrl= '')
    Beedrill = Pokemon(
        name='Beedrill', 
        type='bug, poison', 
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Pidgey = Pokemon(
        name='Pidgey', 
        type='normal, flying', 
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Pidgeotto = Pokemon(
        name='Pidgeotto', 
        type='normal, flying', 
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Pidgeot = Pokemon(
        name='Pidgeot', 
        type='normal, flying', 
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Rattata = Pokemon(
        name='Rattata', 
        type='normal', 
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Raticate = Pokemon(
        name='Raticate', 
        type='normal', 
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Spearow = Pokemon(
        name='Spearow', 
        type='normal, flying', 
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Fearow = Pokemon(
        name='Fearow', 
        type='normal, flying', 
        personality='ambitious',
        bio= '',
        imgUrl= '')   
    Ekans = Pokemon(
        name='Ekans', 
        type='poison', 
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Arbok = Pokemon(
        name='Arbok', 
        type='poison', 
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Pikachu = Pokemon(
        name='Pikachu', 
        type='electric',
        personality='playful',
        bio= '',
        imgUrl= '')
    Raichu = Pokemon(
        name='Raichu', 
        type='electric', 
        personality='playful',
        bio= '',
        imgUrl= '') 
    Sandshrew = Pokemon(
        name='Sandshrew', 
        type='ground', 
        personality='playful',
        bio= '',
        imgUrl= '')
    Sandslash = Pokemon(
        name='Sandslash', 
        type='ground', 
        personality='ambitious',
        bio= '',
        imgUrl= '')
    NidoranF = Pokemon(
        name='Nidoran♀', 
        type='poison', 
        personality='playful',
        bio= '',
        imgUrl= '')
    Nidorina = Pokemon(
        name='Nidorina', 
        type='poison', 
        personality='playful',
        bio= '',
        imgUrl= '')
    Nidoqueen = Pokemon(
        name='Nidoqueen', 
        type='ground, poison', 
        personality='caring',
        bio= '',
        imgUrl= '')
    NidoranM = Pokemon(
        name='Nidoran♂', 
        type='poison', 
        personality='playful',
        bio= '',
        imgUrl= '')
    Nidorino = Pokemon(
        name='Nidorino', 
        type='poison', 
        personality='playful',
        bio= '',
        imgUrl= '')
    Nidoking = Pokemon(
        name='Nidoqueen', 
        type='ground, poison', 
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Clefairy = Pokemon(
        name='Clefairy', 
        type='fairy', 
        personality='caring',
        bio= '',
        imgUrl= '')
    Clefable = Pokemon(
        name='Clefable', 
        type='fairy', 
        personality='caring',
        bio= '',
        imgUrl= '')
    Vulpix = Pokemon(
        name='Vulpix', 
        type='fire', 
        personality='playful',
        bio= '',
        imgUrl= '')
    Ninetales = Pokemon(
        name='Ninetales', 
        type='fire', 
        personality='logical',
        bio= '',
        imgUrl= '')
    Jigglypuff = Pokemon(
        name='Jigglypuff', 
        type='normal, fairy', 
        personality='playful',
        bio= '',
        imgUrl= '')
    Wigglytuff = Pokemon(
        name='Wigglytuff', 
        type='normal, fairy', 
        personality='caring',
        bio= '',
        imgUrl= '')
    Zubat = Pokemon(
        name='Zubat', 
        type='poison, flying', 
        personality='playful',
        bio= '',
        imgUrl= '')
    Golbat = Pokemon(
        name='Golbat', 
        type='poison, flying', 
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Oddish = Pokemon(
        name='Wigglytuff', 
        type='grass, poison', 
        personality='playful',
        bio= '',
        imgUrl= '')
    Gloom = Pokemon(
        name='Gloom', 
        type='grass, poison',
        personality='caring',
        bio= '',
        imgUrl= '')
    Vileplume = Pokemon(
        name='Vileplume', 
        type='grass, poison',
        personality='caring',
        bio= '',
        imgUrl= '')
    Paras = Pokemon(
        name='Golbat', 
        type='bug, grass', 
        personality='caring',
        bio= '',
        imgUrl= '')
    Parasect = Pokemon(
        name='Wigglytuff', 
        type='bug, grass', 
        personality='logical',
        bio= '',
        imgUrl= '')
    Venonat = Pokemon(
        name='Venonat', 
        type='bug, poison',
        personality='logical',
        bio= '',
        imgUrl= '')
    Venomoth = Pokemon(
        name='Venomoth', 
        type='bug, poison',
        personality='logical',
        bio= '',
        imgUrl= '')
    Diglett = Pokemon(
        name='Diglett', 
        type='ground',
        personality='logical',
        bio= '',
        imgUrl= '')
    Dugtrio = Pokemon(
        name='Dugtrio', 
        type='bug, poison',
        personality='logical',
        bio= '',
        imgUrl= '')
    Meowth = Pokemon(
        name='Meowth', 
        type='normal',
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Persian = Pokemon(
        name='Persian', 
        type='normal',
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Psyduck = Pokemon(
        name='Psyduck', 
        type='water',
        personality='playful',
        bio= '',
        imgUrl= '')
    Golduck = Pokemon(
        name='Golduck', 
        type='water',
        personality='logical',
        bio= '',
        imgUrl= '')
    Mankey = Pokemon(
        name='Mankey', 
        type='fighting',
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Primeape = Pokemon(
        name='Primeape', 
        type='fighting',
        personality='ambitious',
        bio= '',
        imgUrl= '')
    
    Growlithe = Pokemon(
        name='Growlithe', 
        type='fire',
        personality='caring',
        bio= '',
        imgUrl= '')
    Arcanine = Pokemon(
        name='Arcanine', 
        type='fire',
        personality='caring',
        bio= '',
        imgUrl= '')
    Poliwag = Pokemon(
        name='Poliwag', 
        type='water',
        personality='playful',
        bio= '',
        imgUrl= '')
    Poliwhirl = Pokemon(
        name='Poliwhirl', 
        type='water',
        personality='logical',
        bio= 'Although it can live in or out of water, Poliwhirl prefers to live underwater where it can escape from danger more easily.',
        imgUrl= '')
    Poliwrath = Pokemon(
        name='Poliwrath', 
        type='water, fighting',
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Abra = Pokemon(
        name='Abra', 
        type='psychic',
        personality='logical',
        bio= '',
        imgUrl= '')
    Kadabra = Pokemon(
        name='Kadabra', 
        type='psychic',
        personality='logical',
        bio= '',
        imgUrl= '')
    Alakazam = Pokemon(
        name='Alakazam', 
        type='psychic',
        personality='logical',
        bio= '',
        imgUrl= '')
    Machop = Pokemon(
        name='Machop', 
        type='fighting',
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Machoke = Pokemon(
        name='Machoke', 
        type='fighting',
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Machamp = Pokemon(
        name='Machamp', 
        type='fighting',
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Bellsprout = Pokemon(
        name='Bellsprout', 
        type='grass, poison',
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Weepinbell = Pokemon(
        name='Weepinbell', 
        type='grass, poison',
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Victreebel = Pokemon(
        name='Victreebel', 
        type='grass, poison',
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Tentacool = Pokemon(
        name='Tentacool', 
        type='water, poison',
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Tentacruel = Pokemon(
        name='Tentacruel', 
        type='water, poison',
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Geodude = Pokemon(
        name='Geodude', 
        type='rock, ground',
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Graveler = Pokemon(
        name='Geodude', 
        type='rock, ground',
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Golem = Pokemon(
        name='Geodude', 
        type='rock, ground',
        personality='ambitious',
        bio= '',
        imgUrl= '')
    Ponyta = Pokemon(
        name='Ponyta', 
        type='fire',
        personality='ambitious',
        bio= 'Ponytas are weak at birth but grow strong as they run all day in fields and on mountains.',
        imgUrl= '')
    Rapidash = Pokemon(
        name='Rapidash', 
        type='fire',
        personality='playful',
        bio= 'Rapidash just loves to run. If it sees something faster than itself, it will give chase at top speed in the hopes of catching up.',
        imgUrl= '')
    Slowpoke = Pokemon(
        name='Slowpoke', 
        type='water, psychic',
        personality='logical',
        bio= 'It catches prey by dipping its tail in water at the side of a river. But it often forgets what it is doing and spends entire days just loafing at the water.',
        imgUrl= '')
    Slowbro = Pokemon(
        name='Slowbro', 
        type='water, psychic',
        personality='logical',
        bio= 'Though usually dim witted, it seems to become inspired if the Shellder on its tail bites down.',
        imgUrl= '')
    Magnemite = Pokemon(
        name='Magnemite', 
        type='electric, steel',
        personality='playful',
        bio= 'It is attracted by electromagnetic waves. Its interest is piqued whenever it senses trainers using their pokegear.',
        imgUrl= '')
    Magneton = Pokemon(
        name='Magneton', 
        type='electric, steel',
        personality='playful',
        bio= 'When three Magnemite link together, their brains also become one. (They do not become three times more intelligent.)',
        imgUrl= '')
    Farfetchd = Pokemon(
        name='Farfetchd', 
        type='normal, flying',
        personality='caring',
        bio= 'It cannot live without the stalk it holds, so it defends the stalk from attackers with its life.',
        imgUrl= '')
    Doduo = Pokemon(
        name='Doduo', 
        type='normal, flying',
        personality='logical',
        bio= 'The brains in its two heads appear to communicate emotions to each other with a telepathic power.',
        imgUrl= '')
    Dodrio = Pokemon(
        name='Dodrio', 
        type='normal, flying',
        personality='logical',
        bio= 'It collects data and plans three times as wisely as a single-brained organism, but it may think too much and become immobilized.',
        imgUrl= '')
    Seel = Pokemon(
        name='Seel', 
        type='water',
        personality='playful',
        bio= 'Loves freezing cold conditions. Relishes swimming in a frigid climate of around 14F degrees. In the daytime, it is often found asleep on the seabed in shallow waters. ',
        imgUrl= '')
    Dewgong = Pokemon(
        name='Dewgong', 
        type='water',
        personality='playful',
        bio= 'It loves frigid seas with ice floes. The colder the temperature, the friskier it gets.',
        imgUrl= '')
    Grimer = Pokemon(
        name='Grimer', 
        type='poison',
        personality='playful',
        bio= 'Its sludgy and rubbery body can be forced through any opening, however small it may be. It enters sewer pipes to drink filthy wastewater.',
        imgUrl= '')
    Muk = Pokemon(
        name='Muk', 
        type='poison',
        personality='playful',
        bio= '	They love to gather in smelly areas where sludge accumulates, making the stench around them worse.',
        imgUrl= '')


    db.session.add(Bulbasaur)
    db.session.add(Ivysaur)
    db.session.add(Venusaur)
    db.session.add(Charmander)
    db.session.add(Charmeleon)
    db.session.add(Charizard)
    db.session.add(Squirtle)
    db.session.add(Wartortle)
    db.session.add(Blastoise)
    db.session.add(Caterpie)
    db.session.add(Metapod)
    db.session.add(Butterfree)

    db.session.commit()

def undo_pokemon():
    db.session.execute('TRUNCATE pokemon RESTART IDENTITY CASCADE;')
    db.session.commit()
