"""empty message

Revision ID: 07b565366609
Revises: d6a2bc2175e1
Create Date: 2022-07-21 16:04:32.551934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b565366609'
down_revision = 'd6a2bc2175e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profileImages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imgUrl', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profileImages')
    # ### end Alembic commands ###
