"""Added matchDate

Revision ID: ba1bd1826f6d
Revises: 63df50c8f893
Create Date: 2022-07-25 13:39:36.932493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1bd1826f6d'
down_revision = '63df50c8f893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('matchTime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'matchTime')
    # ### end Alembic commands ###
