"""added not interested column

Revision ID: b777c28ca381
Revises: ba1bd1826f6d
Create Date: 2022-07-25 15:52:21.374290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b777c28ca381'
down_revision = 'ba1bd1826f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('notInterested', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'notInterested')
    # ### end Alembic commands ###
