"""update all tables

Revision ID: c4db34f44442
Revises: 05de1bf255ef
Create Date: 2022-07-22 12:28:09.126220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4db34f44442'
down_revision = '05de1bf255ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'userId2',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'userId2',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
