"""lowercase profimages

Revision ID: 38fc841d436f
Revises: c4db34f44442
Create Date: 2022-07-22 13:20:29.107330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38fc841d436f'
down_revision = 'c4db34f44442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profileimages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imgUrl', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('profileImages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profileImages',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"profileImages_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('imgUrl', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='profileImages_userId_fkey'),
    sa.PrimaryKeyConstraint('id', name='profileImages_pkey')
    )
    op.drop_table('profileimages')
    # ### end Alembic commands ###
