"""added matched column to Match

Revision ID: 63df50c8f893
Revises: 38fc841d436f
Create Date: 2022-07-23 09:04:50.401802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63df50c8f893'
down_revision = '38fc841d436f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('matched', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'matched')
    # ### end Alembic commands ###
